#!/bin/bash

# https://github.com/yeKcim/my_nautilus_scripts
# License: GNU General Public License V3, 29 June 2007
# Installation:
    # Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
    # Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Dependency: inkscape
# Convert svg
IFS="
"
################################################
#        notification depends of system        #
################################################
function notif { 
    # the script is running in a term
    if [ $(env | grep '^TERM') ]; then printf "\n#### $(basename -- "$0") notification ####\n  ⇒  $1\n\n"
    # in x, notifications
    else
        if [ $(which notify-send) ]; then notify-send "$1"
        elif [ $(which zenity) ]; then
            echo "message:$1" | zenity --notification --listen &
        elif [ $(which kdialog) ]; then
            kdialog --title "$1" --passivepopup "This popup will disappear in 5 seconds" 5 &
        elif [ $(which xmessage) ]; then xmessage "$1" -timeout 5
        # You don't have notifications? I don't care, I need to tell you something!
        else
            echo "$1" > "$(basename -- $0)_notif.txt"
        fi
    fi
}

################################################
#               dependency check               #
################################################
function depend_check {
    if [ ! $(which $1) ]; then
        notif "Error: Could not find \"$1\" application."
        exit 1
    fi
}

################################################
#         do not overwrite with output         #
################################################
function do_not_overwrite {
    out="$1"
    while [[ -a "$out" ]]; do
        when=$(date +%Y%m%d-%H:%M:%S)
        [[ -f "$out" ]] && out="${out%.*}#$when.${out##*.}" || out="$out#$when"
    done
    echo "$out"
}

################################################
#                    script                    #
################################################
# check if input files > 1
if (( $# <= "0" )); then 
    notif "$# file selected, \"$(basename -- $0)\" needs at least 1 input file" 
    exit 1
fi

# conversion type?
argfromscriptname=$(echo "$0" | sed -n 's/.*\[\(.*\)\].*/\1/p')
case $argfromscriptname in
    "emf") formatout="M";;
    "eps") formatout="E";;
    "pdf") formatout="A";;
    "svg simple") formatout="l";;
    "wmf") formatout="m";;
    *) formatout="A";;
esac

output_ext=$(echo "$argfromscriptname" | cut -d ' ' -f 1)
[ $output_ext == "svg" ] && output_ext="simple.svg" || output_ext=$output_ext

depend_check inkscape

directory="$(pwd)"
mime_error=0; mime_error_file=""
for arg
do
    # input/output
    input=$(readlink -f -- "$arg")
    input_filename=$(basename -- "$input")
    output=$(do_not_overwrite "$directory/${input_filename%.*}.$output_ext")

    type=$(file --mime-type -b -- "$input" | cut -d "/" -f2)
    typez=$(file --mime-type -bz "$input" | cut -d "/" -f2)    

    if [ "$type" == "gzip" ] && [ "$typez" == "svg+xml" ]; then
        work="1"
    elif [ "$type" == "svg+xml" ]; then
        work="1"
    else work="0"
    fi
    
    if [[ $work != "0" ]]; then
        inkscape -"$formatout" "$output" "$input"
    else
            ((mime_error++)); mime_error_file="$mime_error_file \"$input_filename\""
    fi
done

# notif mime errors
if [[ $mime_error != 0 ]]; then
    [[ $mime_error == 1 ]] && notif "Error: $mime_error_file mimetype not supported"
    [[ $mime_error > 1 ]] && [[ $mime_error < $# ]] && notif "Error: mimetype not supported ($mime_error/$# files:$mime_error_file)"
    [[ $mime_error > 1 ]] && [[ $mime_error = $# ]] && notif "Error: Selected files mimetype not supported"
fi
