#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Dependency: pdftk
# Burst multiple pages pdf in multiple files
IFS="
"

# Dependency: pdftk
for command in pdftk
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

directory=$(pwd)
for arg
do
	ext=${arg##*.}
	if [ "$ext" == "pdf" ] || [ "$ext" == "PDF" ]; then
		mkdir "${arg}_explode"
		cd "${arg}_explode"
		pdftk "$directory/$arg" burst
		rm -f "doc_data.txt"
		cd $directory
	fi
done
