#!/bin/bash
# 2015-01-15 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Rotate pdf
IFS="
"
angle="north"

for arg
do
	type=$(mimetype -bM "$arg" | cut -d "/" -f2)
	################################################
	#               input file is pdf              #
	################################################
	if [ $type == "pdf" ]; then
		for command in pdftk # add here all dependencies only with space separator
		do
			################################################
			#              Dependencies check              #
			################################################
			if [ ! $(which $command) ]; then
				notify-send "Error: Could not find \"$command\" application."
				exit 1
			fi
		done
		################################################
		#          Everything is ok, do the job        #
		################################################
		pdftk "$arg" cat 1-end$angle output "${arg%.*}_$angle.${arg##*.}"
	################################################
	#        input mimetype is not supported       #
	################################################
	else
		notify-send "Error: $arg mimetype is not supported"
	fi
done
