#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Resize pictures
IFS="
"

# Dependency: convert (imagemagick)
for command in convert
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

size="480"
for arg
do
	convert -resize "$size"x"$size" "$arg" "${arg%.*}_$size.${arg##*.}"
done
