#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Convert picture format
IFS="
"

# Dependency: convert (imagemagick)
for command in convert
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

out="jpg"
for arg
do
	ext=${file##*.}
	if [ "$ext" != "$out" ]; then
	    convert "$arg" -background white -flatten "${arg%.*}.$out"
	fi
done
