#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Rotate pictures
IFS="
"
################################################
#        notification depends of system        #
################################################
function notif { 
	# the script is running in a term
	if [ $(env | grep '^TERM') ]; then
		printf "Notification: \"$1\"\n"
	# in x, notifications
	else
		if [ $(which notify-send) ]; then
			notify-send "$1"
		elif [ $(which zenity) ]; then
			echo "message:$1" | zenity --notification --listen &
		elif [ $(which kdialog) ]; then
			kdialog --title "$1" --passivepopup "This popup will disappear in 5 seconds" 5 &
		elif [ $(which xmessage) ]; then
			xmessage "$1" -timeout 5
		# You don't have notifications? I don't care, I need to tell you something!
		else
			echo "$1" > "$(basename $0)_notif.txt"
		fi
	fi
}

argfromscriptname=$(echo "$0" | sed -n 's/.*\[\(.*\)°\].*/\1/p')

for arg
do
	################################################
	#          input mimetype is supported         #
	################################################
	type=$(mimetype -bM "$arg" | cut -d "/" -f1)
	case $type in
		"image") work="1";;
		*) work="0";;
	esac

	if [ $work != "0" ]; then
		################################################
		#              Dependencies check              #
		################################################
		for command in convert # add here all dependencies only with space separator
		do
			if [ ! $(which $command) ]; then
				notif "Error: Could not find \"$command\" application."
				exit 1
			fi
		done
		################################################
		#          Everything is ok, do the job        #
		################################################
		convert -rotate $argfromscriptname "$arg" "${arg%.*}_$argfromscriptname.${arg##*.}"

	################################################
	#        input mimetype is not supported       #
	################################################
	else
		notif "Error: $arg mimetype is not supported"
	fi
done
