#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# add background in picture with alpha
IFS="
"

# Dependency: convert (imagemagick)
for command in convert
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

color="white"
for arg
do
	convert "$arg" -background $color -flatten "${arg%.*}_$color.${arg##*.}"
done
