#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Convert svg to jpg
IFS="
"

# Dependency: convert (imagemagick) and inkscape
for command in inkscape convert
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

resolution="600"
for arg
do
	ext=${arg##*.}
	if [ "$ext" == "svg" ] || [ "$ext" == "SVG" ] || [ "$ext" == "svgz" ] || [ "$ext" == "SVGZ" ]; then
	    fifo_file="${arg%.*}_${resolution}dpi_fifo.png"
	    mkfifo "$fifo_file"
	    inkscape -d "$resolution" -e "$fifo_file" "$arg" < /dev/null &
	    convert "$fifo_file" -background white -flatten "${arg%.*}_${resolution}dpi.jpg"
	    rm -f "$fifo_file"
	fi
done
