#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
    # Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
    # Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# move fonts to ~/.fonts directory
IFS="
"
################################################
#        notification depends of system        #
################################################
function notif { 
    # the script is running in a term
    if [ $(env | grep '^TERM') ]; then printf "\n#### $(basename "$0") notification ####\n  ⇒  $1\n\n"
    # in x, notifications
    else
        if [ $(which notify-send) ]; then notify-send "$1"
        elif [ $(which zenity) ]; then
            echo "message:$1" | zenity --notification --listen &
        elif [ $(which kdialog) ]; then
            kdialog --title "$1" --passivepopup "This popup will disappear in 5 seconds" 5 &
        elif [ $(which xmessage) ]; then xmessage "$1" -timeout 5
        # You don't have notifications? I don't care, I need to tell you something!
        else
            echo "$1" > "$(basename $0)_notif.txt"
        fi
    fi
}

################################################
#                    script                    #
################################################
# check if input files > 1
if (( $# <= "0" )); then 
    notif "$# file selected, \"$(basename $0)\" needs at least 1 input file" 
    exit 1
fi

#  Create directory ~/.fonts if doesn't exist, what if rights are not good?
if [[ ! -a ~/.fonts ]]; then
    mkdir -p ~/.fonts
fi

for arg
do
    # input/output
    [ $(env | grep '^TERM') ] && input=$(readlink -f "$arg") || input="$arg"
    input_filename=$(basename "$input")

    # mimetype
    type=$(file --mime-type -b "$input" | cut -d "/" -f2)
    case $type in
        "x-font-ttf") work="1";;
        "x-font-otf") work="1";;
        *) work="0";;
    esac
    
    # input mimetype is supported
    if [ $work != "0" ]; then
        if [[ -f ~/.fonts/$input_filename ]]; then
            notif "\"$input_filename\" already installed."
        else
            cp "$input" ~/.fonts
            # does script worked fine?
            if [[ -f ~/.fonts/$input_filename ]]; then notif "\"$input_filename\" installed."
            else notif "Error: Cannot install \"$input_filename\"."
            fi
        fi
    
    # input mimetype is not supported
    else
        notif "Error: \"$input_filename\" mimetype is not supported"
    fi

done
