#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# Rotate videos
IFS="
"

# Dependency: avconv (libav-tools)
for command in avconv
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

angle="3"
for arg
do
	avconv -i "$arg" -vf "transpose=$angle" "${arg%.*}_rot$angle.${arg##*.}"
done
