#!/bin/bash
# https://github.com/yeKcim/my_nautilus_scripts
# License: GNU General Public License V3, 29 June 2007
# Installation:
    # Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
    # Nemo:     copy this file in ~/.gnome2/nemo-scripts/          and chmod +x it
    # Caja:     copy this file in ~/.config/caja/scripts/          and chmod +x it
# Dependency: pdftotext (from poppler-utils) unoconv or soffice
# extract text from opendocument, ooxml, msoffice document or pdf
IFS="
"
################################################
#        notification depends of system        #
################################################
function notif { 
    # the script is running in a term
    if [ $(env | grep '^TERM') ]; then printf "\n#### $(basename -- "$0") notification ####\n  ⇒  $1\n\n"
    else # in x, notifications
		if   hash notify-send 2>/dev/null; then notify-send "$1"
		elif hash zenity 2>/dev/null; then { echo "message:$1" | zenity --notification --listen & }
		elif hash kdialog 2>/dev/null; then { kdialog --title "$1" --passivepopup "This popup will disappear in 5 seconds" 5 & }
		elif hash xmessage 2>/dev/null; then xmessage "$1" -timeout 5
        else echo "$1" > "$(basename -- $0)_notif.txt"
        fi
    fi
}
################################################
#               dependency check               #
################################################
function depend_check {
    for arg; do
		hash "$arg" 2>/dev/null || { notif >&2 "Error: Could not find \"$arg\" application."; exit 1; }
    done    
}
################################################
#         do not overwrite with output         #
################################################
function do_not_overwrite {
    out="$1"
    while [[ -a "$out" ]]; do
        when=$(date +%Y%m%d-%H:%M:%S)
        [[ -f "$out" ]] && out="${out%.*}#$when.${out##*.}" || out="$out#$when"
    done
    echo "$out"
}
################################################
#          check if input files > min          #
################################################
function nb_files_check {
    nb_files="$1"
    min_nb_files="$2"
    if (( $1 < $2 )); then 
        [[ $2 == 1 ]] && notif "$1 file selected, \"$(basename -- $0)\" needs at least one input file" || notif "$1 file selected, \"$(basename -- $0)\" needs at least $2 input files" 
        exit 1
    fi 
}
################################################
#              error notifications             #
################################################
function error_check {
    nb_files="$1"
    error_message="Error: $2"
    nb_error="$3"
    name_error_files="$4"

    if [[ $nb_error != 0 ]]; then
        [[ $nb_error == 1 ]] && error_message="$error_message:$name_error_files"
        [[ $nb_error > 1 ]] && [[ $nb_error < $nb_files ]] && error_message="$error_message ($nb_error/$nb_files files: $name_error_files)"
        [[ $nb_error > 1 ]] && [[ $nb_error = $nb_files ]] && error_message="$error_message (All selected files)"
    notif "$error_message"
    fi
}
################################################
#      error write rights notifications        #
################################################
function writeout_right_check {
    out=$(readlink -f -- "$1")
    outdir="${out%/*}"
    [[ ! -w "$outdir" ]] && echo "1" || echo "0"
}

################################################
#                    script                    #
################################################
nb_files_check $# 1

directory="$(pwd)"
mime_error=0; mime_error_file=""
writeout_error=0; writeout_error_file=""
for arg
do
    # input/output
    input=$(readlink -f -- "$arg")
    input_filename=$(basename -- "$input")
    output=$(do_not_overwrite "${input_filename%.*}.txt")

    if [[ $(writeout_right_check "$output") == "1" ]]; then
        ((writeout_error++))
        writeout_error_file="$writeout_error_file \"$input_filename\""
        continue
    fi
    
    type=$(file --mime-type -b -- "$input" | cut -d "/" -f2)
    
    case $type in # input mimetype is supported
        "octet-stream") # can't find from mime-type use extension
            case "${input##*.}" in
                    "docx") command="unoconv" ;;
                    "xlsx") command="unoconv" ;;
                    "pptx") command="unoconv" ;;
                    "odt"|"ods"|"odp") command="unoconv" ;;
                    "doc"|"xls"|"ppt") command="unoconv" ;;
                    *) ((mime_error++)); mime_error_file="$mime_error_file \"$input_filename\"" ;;
            esac ;;
        "zip") [[ $(file --mime-type -bz -- "$input") == "application/xml" ]] && command="unoconv" ;;
        "vnd.openxmlformats-officedocument.presentationml.presentation") command="unoconv" ;; # pptx
        "vnd.openxmlformats-officedocument.wordprocessingml.document") command="unoconv" ;; # docx
        "vnd.openxmlformats-officedocument.spreadsheetml.sheet") command="unoconv" ;; # xlsx
        "vnd.oasis.opendocument.text"|"vnd.oasis.opendocument.presentation"|"vnd.oasis.opendocument.spreadsheet") command="unoconv" ;; # odt|odp|ods
        "msword"|"vnd.ms-powerpoint"|"vnd.ms-office"|"vnd.ms-excel") command="unoconv" ;; # doc|ppt|xls
        "pdf")
            depend_check pdftotext
            pdftotext -layout "$input" "$output" ;;
        "rtf")
            depend_check unrtf
            unrtf --text "$input" | cat >> "$output" ;;    
        *) # input mimetype is not supported
            ((mime_error++)); mime_error_file="$mime_error_file \"$input_filename\"" ;;
    esac

    if [[ $command == "unoconv" ]]; then
        [[ $(ps aux | grep -c soffice) > 1 ]] && bug37531="-env:UserInstallation=file:///tmp/bug37531" || bug37531=""
        if [[ $command == "unoconv" ]] && [[ $bug37531 == "" ]]; then
            unoconv -o "$output_file" -f txt "$input"
        else
            depend_check soffice
            output_dir_temp=$(do_not_overwrite "$directory/${input_filename%.*}_temp")
            libreoffice --headless --convert-to txt $bug37531 --outdir "$output_dir_temp" "$input"
            mv -- "$output_dir_temp/$output_filename" "$output_file"
            rm -rf -- "$output_dir_temp"
        fi
    fi

done

error_check "$#" "Mimetype not supported" "$mime_error" "$mime_error_file"
error_check "$#" "Can't write in output directory" "$writeout_error" "$writeout_error_file"
