#!/bin/bash
# 2015-01-14 - by yeKcim
# Installation:
	# Nautilus: copy this file in ~/.local/share/nautilus/scripts/ and chmod +x it
	# Nemo: copy this file in ~/.gnome2/nemo-scripts/ and chmod +x it
# try to delete blank background in picture
IFS="
"
# Dependency: convert (imagemagick)
for command in convert
do
	if [ ! $(which $command) ]
	then
		notify-send "Error: Could not find \"$command\" application."
		exit 1
	fi
done

color="white"
fuzz="40"
for arg
do
	convert "$arg" -bordercolor $color -border 1x1 -alpha set -channel RGBA -fuzz $fuzz% -fill none -floodfill +0+0 white -shave 1x1 "${arg%.*}_$color→α_fuzz$fuzz.${arg##*.}"
done
